version: '3.9'


services:
    api:
        container_name: api
        image: api_express
        build: .
        ports:
            - 3000:3000
        depends_on:
            - db        
        environment:
            - DB_USER=luizassano
            - DB_PASSWORD=1234
            - DB_HOST=localhost
            - DB_PORT=5432
            - DB=products_management
    db:
        container_name: db
        image: postgres:12
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=luizassano
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=products_management   
        volumes:
            - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql